### ISSUE TITLE
Remove hardcoded versions from ansible depencies

### ISSUE THREAD

**Issue by ivandov** [IBM/zmodstack-deploy#68]
### Description
I noticed that the ansible galaxy dependencies have hard-coded versions. 

```yaml
---
collections:
  - name: kubernetes.core
    version: 2.3.2
  - name: community.general
    version: 6.3.0
  - name: community.okd
    version: 2.2.0
  - name: containers.podman
    version: 1.10.2
  - name: ibm.cloudcollection
  - name: community.crypto
```

### Potential Solutions
If a specific version isn't needed, then we should always use the latest version of any ansible dependencies.
