### ISSUE TITLE
Expose z/OS Connect Designer through Wazi DevSpaces Workspace

### ISSUE THREAD

**Issue by ivandov** [IBM/zmodstack-deploy#69]
### Description
The new release of z/OS Connect now supports running the Designer UI through Wazi Devspaces. Our current automation stands up z/OS Connect Designer and Server on the boot node, which I do not expect our clients to use in this way. We should ensure that all usage of z/OS Connect happens through the OCP interfaces.

### Potential Solutions
1. Reach out to z/OS Connect team and understand proper usage and documentation with Wazi DevSpaces
2. Deploy z/OS Connect Designer more "natively" through a `Deployment` resource and any applicable `Routes`.

### Additional Context
Snippet for a `Devfile` that can bring up a z/OS Connect Designer container

```yaml
schemaVersion: 2.2.0
metadata:
  name: wazi-devspaces
  namespace: <dynamically-generated?>
attributes:
  controller.devfile.io/devworkspace-config:
    name: devworkspace-config
    namespace: openshift-operators
  controller.devfile.io/storage-type: per-user
components:
  - attributes:
      controller.devfile.io/merge-contribution: true
  - container:
      endpoints:
        - exposure: public
          name: zosconnect-ui
          path: /zosConnect/designer/
          protocol: http
          targetPort: 9080
      env:
        - name: ZCON_DESIGNER_PROJECT
          value: /projects/zopeneditor-sample/apiProjectWorkspace/apiProject/start
      image: icr.io/zosconnect/ibm-zcon-designer:3.0.70
      memoryLimit: 4927M
      mountSources: true
      sourceMapping: /projects
    name: zosconnect
```
